- name: Ensure keepalived service is stopped
  ansible.builtin.service:
    name: keepalived
    state: stopped
  register: stop_keepalived_result
  failed_when:
    - stop_keepalived_result.failed == true
    - '"Could not find the requested service" not in stop_keepalived_result.msg'
