- name: Ensure keepalived service is started
  ansible.builtin.service:
    name: keepalived
    state: started
  register: start_keepalived_result
  failed_when:
    - start_keepalived_result.failed == true
    - '"Could not find the requested service" not in start_keepalived_result.msg'
