- name: Update apt packages
  ansible.builtin.apt:
    autoclean: true
    autoremove: true
    clean: true
    update_cache: true
    upgrade: dist

- name: Check if reboot is needed
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: updates_reboot_required

- name: Reboot
  ansible.builtin.reboot:
  when: updates_reboot_required.stat.exists
