---
dir_loc: '/opt/pihole'
firewall_itmes:
  - dns
  - http
  - https

pihole_environment_variables:
  # refernce https://github.com/pi-hole/docker-pi-hole
  # Some more situational and uncommon vars are lefted 
  # commment and provided here for your reference when 
  # creating your deployment(s)
  TZ: 'UTC'  # Set your timezone
  WEBPASSWORD: ''  # Password for the Pi-hole admin interface; leave empty for no password
  PIHOLE_DNS_: '8.8.8.8;8.8.4.4'  # List of DNS providers
  DNSMASQ_LISTENING: 'all'  # Interface listening behavior
  VIRTUAL_HOST: 'pi.hole'  # Hostname for the web interface
  PROXY_LOCATION: '/'  # Proxy location for the web interface
  ServerIP: ''  # IP address of the server hosting Pi-hole
  IPv6: 'True'  # Enable IPv6 support
  FTLCONF_LOCAL_IPV4: ''  # Local IPv4 address for FTLDNS
  FTLCONF_LOCAL_IPV6: ''  # Local IPv6 address for FTLDNS

  # Optional Variables
  TEMPERATUREUNIT: 'c'  # Temperature unit; 'c' for Celsius, 'f' for Fahrenheit
  ADMIN_EMAIL: ''  # Admin email address
  WEBTHEME: 'default-light'  # Theme for the web interface
  CUSTOM_CACHE_SIZE: '10000'  # Custom DNS cache size
  DHCP_ACTIVE: 'false'  # Enable DHCP server
  DHCP_START: '192.168.56.201'  # Start of DHCP address range
  DHCP_END: '192.168.56.251'  # End of DHCP address range
  DHCP_ROUTER: '192.168.56.1'  # DHCP router (gateway) IP address
  DHCP_LEASETIME: '24'  # DHCP lease time in hours
  PIHOLE_DOMAIN: 'lan'  # Local domain name
  DHCP_IPv6: 'true'  # Enable IPv6 DHCP server
  DHCP_rapid_commit: false #Enable DHCPv4 rapid commit (fast address assignment)
  DNSSEC: 'false'  # Enable DNSSEC
  REV_SERVER: 'false'  # Enable conditional forwarding
  REV_SERVER_CIDR: '192.168.56.0/24'  # CIDR range for reverse DNS
  REV_SERVER_TARGET: '192.168.56.1'  # IP of the upstream DNS server for conditional forwarding
  REV_SERVER_DOMAIN: 'lan'  # Local domain name for reverse DNS

  # Advanced Variables
  FTLCONF_REPLY_ADDR4: ''  # IPv4 address to use for replies
  FTLCONF_REPLY_ADDR6: ''  # IPv6 address to use for replies
  FTLCONF_RATE_LIMIT: '1000/60'  # Rate limit for queries
  FTLCONF_MAXDBDAYS: '365'  # Maximum days to retain query logs in the database
  FTLCONF_PRIVACYLEVEL: '0'  # Privacy level (0â€“3)
  FTLCONF_ANALYZE_ONLY_A_AND_AAAA: 'false'  # Analyze only A and AAAA queries
  FTLCONF_RESOLVE_IPV6: 'true'  # Enable resolving IPv6 addresses
  FTLCONF_RESOLVE_IPV4: 'true'  # Enable resolving IPv4 addresses
  FTLCONF_DNS_BOGUS_PRIV: 'true'  # Enable filtering of bogus private DNS queries
  FTLCONF_DNS_FQDN_REQUIRED: 'false'  # Require Fully Qualified Domain Names for DNS queries

  #INTERFACE: #If you're trying to use DHCP with --net host mode then you may have to customize this or DNSMASQ_LISTENING.
  #WEB_PORT: #This will break the 'webpage blocked' functionality of Pi-hole however it may help advanced setups like those running synology
  #WEB_BIND_ADDR: #Lighttpd's bind address.
  #SKIPGRAVITYONBOOT: Use this option to skip updating the Gravity Database when booting up the container
  #CORS_HOSTS: #List of domains/subdomains on which CORS is allowed. Wildcards are not supported
  #FTL_CMD: Customize the options with which dnsmasq gets started

  # Experimental Variables
  FTLCONF_NFTABLES: 'false'  # Use nftables instead of iptables
  FTLCONF_SHM_SIZE: '512'  # Shared memory size in MB
  FTLCONF_DATABASE_MAX_SIZE: '10485760'  # Maximum database size in KB (10GB default)

  ### only uncomment if you know what you are doing ####
  #DNSMASQ_USER:
  #PIHOLE_UID:
  #PIHOLE_GID:
  #WEB_UID:
  #WEB_GID:
  #WEBLOGS_STDOUT: